loop_pdf:
  no_auto_commit: True
  restart_only_afternoon: True
weibo_aggregator:
  pause_before_restart: 60
daily_summary:
  pause_before_restart: 600
novel_place_holder:
  custom_setup_name: aggregate
douban:
  pause_before_restart: 60
forward:
  daily_restart: True
subscription_v3:
  pause_before_restart: 30
